version: 2

project_name: unycloud

env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - GOTOOLCHAIN=go1.26.6

before:
  hooks:
    - sh -c "cd frontend && pnpm install --frozen-lockfile"
    - sh -c "cd frontend && pnpm run build"
    - sh -c "scripts/csp-audit.sh"

builds:
  - main: main.go
    binary: unycloud
    ldflags:
      - -s -w -X github.com/filebrowser/filebrowser/v2/version.Version={{ .Version }} -X github.com/filebrowser/filebrowser/v2/version.CommitSHA={{ .ShortCommit }}
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
      - riscv64
    goarm:
      - "5"
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: openbsd
        goarch: riscv64
      - goos: windows
        goarch: arm
      - goos: freebsd
        goarch: arm

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    formats: ["tar.gz"]
    files:
      - LICENSE
      - README.md
    format_overrides:
      - goos: windows
        formats: ["zip"]

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
