services:
  unycloud:
    container_name: unycloud
    image: unycloud:local
    build:
      context: .
    networks:
      - unycloud
    ports:
      - 8000:80
    volumes:
      - unycloud-data:/srv
      - unycloud-config:/config
      - unycloud-database:/database
    environment:
      - FB_REDIS_CACHE_URL=redis://default:${UNYCLOUD_REDIS_PASSWORD:?set UNYCLOUD_REDIS_PASSWORD in .env}@redis:6379 # Use rediss:// for ssl

  redis:
    container_name: redis
    image: redis:8.4-alpine
    networks:
      - unycloud
    environment:
      - UNYCLOUD_REDIS_PASSWORD=${UNYCLOUD_REDIS_PASSWORD:?set UNYCLOUD_REDIS_PASSWORD in .env}
    command:
      - sh
      - -c
      - |
        cat > /tmp/users.acl <<EOF
        user default on >$$UNYCLOUD_REDIS_PASSWORD ~* +@all
        EOF
        redis-server --aclfile /tmp/users.acl

networks:
  unycloud:

volumes:
  unycloud-data:
  unycloud-config:
  unycloud-database:
